package com.example.stardust_springboot.admin.audit;

public enum AdminAuditAction {
    USER_CREATE, USER_UPDATE, USER_BAN, USER_UNBAN, USER_DISABLE, USER_RESTORE,
    USER_DELETE, USER_RESET_PASSWORD, USER_ROLES_UPDATE,
    CONVERSATION_VIEW, CONVERSATION_DELETE,
    FILE_DELETE, RAG_DOCUMENT_RETRY, RAG_VECTOR_REMOVE,
    PROVIDER_CREATE, PROVIDER_UPDATE, PROVIDER_STATUS_UPDATE,
    MODEL_CREATE, MODEL_UPDATE, MODEL_STATUS_UPDATE
}
