package com.example.stardust_springboot.conversation.entity;

public enum AttachmentType {
    FILE,
    IMAGE,
    /** File generated by the assistant (AI artifact) and attached to its message. */
    OUTPUT
}
